require('fs').mkdirSync(require('path').join(__dirname,'results'),{recursive:true});
const fs=require('fs'),http=require('http'),path=require('path'),assert=require('assert'),{chromium}=require('playwright');
const root=require('path').resolve(__dirname,'..');
const server=http.createServer((req,res)=>{const file=path.join(root,new URL(req.url,'http://localhost').pathname);try{const body=fs.readFileSync(file.endsWith('/')?file+'index.html':file);res.setHeader('Content-Type',file.endsWith('.css')?'text/css':file.endsWith('.js')?'text/javascript':'text/html');res.end(body)}catch{res.statusCode=404;res.end('Missing')}});
async function main(){await new Promise(r=>server.listen(8765,'127.0.0.1',r));const browser=await chromium.launch({headless:true,executablePath:process.env.RESTAURANT_CHROMIUM_PATH||(fs.existsSync('/tmp/chromium')?'/tmp/chromium':undefined),args:['--no-sandbox']});let checks=0;const context=await browser.newContext({serviceWorkers:'block',hasTouch:true,viewport:{width:834,height:1194},screen:{width:834,height:1194}});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
await context.route('https://**',route=>route.fulfill({status:200,body:'',contentType:'text/javascript'}));
await context.route('**/scripts/restaurant-auth123.js*',route=>route.fulfill({body:'window.restaurantAuth123={shared:true,connect:async()=>window.mockDb};',contentType:'text/javascript'}));
await page.addInitScript(()=>{const owner='11111111-1111-4111-8111-111111111111';const item='22222222-2222-4222-8222-222222222222',cooked='88888888-8888-4888-8888-888888888888';const data={profiles:[{id:owner,full_name:'Test Cashier',role:'admin',status:'active'}],restaurant_members121:[],restaurant_presentation121:[],menu_categories104:[],menu_items104:[],pos_stock118:[],menu_ingredients105:[{id:'33333333-3333-4333-8333-333333333333',version:1,data:{code:'I',name:'Dry taco ingredients',currency:'LAK',unit:'kg',cost:30000,inventoryItemId118:item,inventoryFactor118:1}}],inventory_items104:[{id:item,data:{code:'I',name:'Dry taco ingredients',currency:'LAK',unit:'kg',cost:30000}},{id:cooked,data:{code:'C',name:'Cooked taco filling',currency:'LAK',unit:'kg',prepared124:true,cost:60000,fullPreparedCost124:80000}}],inventory_movements104:[{id:'receipt',data:{itemId:item,kind:'in',quantity:10,cost:30000},created_at:'2026-10-09T01:00:00Z'},{id:'production',data:{itemId:cooked,kind:'in',quantity:2,cost:60000},created_at:'2026-10-09T01:00:00Z'}],restaurant_batches124:[{id:'44444444-4444-4444-8444-444444444444',output_item_id:cooked,data:{name:'Taco filling',date:'2026-10-09',outputQuantity:2,stockUnit:'kg',currency:'LAK',ingredientTotal:120000,fullTotal:160000,ingredientUnitCost:60000,fullUnitCost:80000,cookingAdditionPercent:100/3,costMode:'actual'}}],restaurant_waste124:[]};window.mockFixtures=data;window.mockDb={auth:{onAuthStateChange(){},getSession:async()=>({data:{session:{user:{id:owner,email:'test@example.com'}}}}),signOut:async()=>({})},from(table){const q={select(){return q},order(){return q},eq(){return q},maybeSingle:async()=>({data:data[table]?.[0]||null}),single:async()=>({data:data[table]?.[0]||null}),then(resolve){return Promise.resolve({data:data[table]||[]}).then(resolve)}};return q},rpc:async()=>({error:{message:'failed to fetch'}})};window.supabase={};window.OJM_SUPABASE_URL='https://fixture.supabase.co';});
await page.goto('http://127.0.0.1:8765/');await page.waitForFunction(()=>!!window.restaurantAccounting124&&document.querySelector('#restaurantApp')?.hidden===false&&document.body.classList.contains('tablet118'));
const results=[];
for(const [w,h,label] of [[834,1194,'ipad-portrait'],[1194,834,'ipad-landscape'],[1366,1024,'ipad-pro-landscape'],[1280,800,'tablet-landscape'],[800,1280,'tablet-portrait']]){
 await page.setViewportSize({width:w,height:h});await page.evaluate(()=>{switchTab('pos118');pos118.state.tab='Sales';pos118.state.sub='New Order';pos118.render()});
 await page.waitForFunction(()=>document.querySelector('#tabletMenu118')?.parentElement?.classList.contains('pos-main-tabs118'));
 assert.equal(await page.locator('.module-header').isVisible(),false);checks++;
 assert.equal(await page.locator('#tabletMenu118').count(),1);checks++;
 assert.equal(await page.locator('#tabletMenu118').isVisible(),true);checks++;
 await page.locator('#tabletMenu118').click();
 await page.waitForFunction(()=>document.querySelector('#appSidebar').getBoundingClientRect().left>=0);
 assert.equal(await page.locator('#tabletMenu118').getAttribute('aria-expanded'),'true');checks++;
 assert.equal(await page.locator('#appSidebar').getAttribute('aria-hidden'),'false');checks++;
 assert.equal(await page.evaluate(()=>document.querySelector('#appSidebar').inert),false);checks++;
 await page.locator('#sidebarScrim').click({position:{x:w-12,y:100}});
 await page.waitForFunction(()=>document.querySelector('#appSidebar').getBoundingClientRect().right<=0);
 assert.equal(await page.locator('#tabletMenu118').getAttribute('aria-expanded'),'false');checks++;
 assert.equal(await page.evaluate(()=>document.querySelector('#appSidebar').inert),true);checks++;
 await page.locator('#tabletMenu118').click();await page.keyboard.press('Escape');assert.equal(await page.locator('#tabletMenu118').getAttribute('aria-expanded'),'false');checks++;
 const style=await page.evaluate(()=>({background:getComputedStyle(document.querySelector('.workspace-scroll')).backgroundColor,inputBackground:getComputedStyle(document.querySelector('.pos-filter118 input')).backgroundColor,inputFont:getComputedStyle(document.querySelector('.pos-filter118 input')).fontFamily,headingFont:getComputedStyle(document.querySelector('.pos-card118 h2')).fontFamily,headingColor:getComputedStyle(document.querySelector('.pos-card118 h2')).color,tablet:restaurantAccounting124.tablet(),overflow:document.documentElement.scrollWidth>innerWidth+1}));
 assert.equal(style.background,'rgb(243, 244, 239)');assert.equal(style.inputBackground,'rgb(255, 252, 246)');assert(style.inputFont.includes('Plus Jakarta Sans'));assert(style.headingFont.includes('Georgia'));assert.equal(style.headingColor,'rgb(33, 75, 55)');assert(style.tablet);assert(!style.overflow);checks+=7;
 await page.evaluate(()=>{document.activeElement?.blur();document.querySelector('.workspace-scroll').scrollTop=0});await page.screenshot({path:path.join(__dirname,'results','accounting-pos-'+label+'.png')});results.push({label,...style});
 await page.evaluate(()=>switchTab('inv-preparation124'));await page.waitForFunction(()=>document.querySelector('#tabletMenu118')?.parentElement?.id==='categoryTabShell');checks++;
 const table=await (await page.waitForFunction(()=>{const e=document.querySelector('#inv-preparation124 th');if(!e)return false;const s=getComputedStyle(e);return s.backgroundColor==='rgb(0, 133, 99)'&&{background:s.backgroundColor,color:s.color}})).jsonValue();assert.equal(table.background,'rgb(0, 133, 99)');assert.equal(table.color,'rgb(255, 255, 255)');checks+=2;
 await page.locator('#tabletMenu118').click();await page.locator('#nav-module-menu .nav-header').click();await page.waitForFunction(()=>!document.body.classList.contains('restaurant-nav-open'));checks++;
 await page.evaluate(()=>switchTab('restaurant-settings'));await page.waitForFunction(()=>document.querySelector('#tabletMenu118')?.parentElement?.classList.contains('settings-tabs121'));checks++;
 await page.evaluate(()=>switchTab('restaurant-overview'));await page.waitForFunction(()=>document.querySelector('#tabletMenu118')?.parentElement?.classList.contains('restaurant-home-tabs124'));checks++;
}
await page.evaluate(()=>{bannerRows.brand={theme:'dark'};applyBrand121();settingsTab121='branding';switchTab('restaurant-settings')});assert.equal(await page.locator('[name=theme]').count(),0);assert.equal(await page.evaluate(()=>document.body.classList.contains('restaurant-dark121')),false);checks+=2;
assert.deepEqual(errors,[]);checks++;
fs.writeFileSync(require('path').join(__dirname,'results','accounting-layout-results.json'),JSON.stringify({checks,status:'passed',results},null,2));console.log(checks+' Accounting palette and tablet navigation checks passed');await browser.close();server.close()}
main().catch(e=>{console.error(e);server.close();process.exit(1)});
