require('fs').mkdirSync(require('path').join(__dirname,'results'),{recursive:true});
const fs=require('fs'),http=require('http'),path=require('path'),assert=require('assert'),{chromium}=require('playwright');
const root=require('path').resolve(__dirname,'..');
const server=http.createServer((req,res)=>{const file=path.join(root,new URL(req.url,'http://localhost').pathname);try{const body=fs.readFileSync(file.endsWith('/')?file+'index.html':file);res.setHeader('Content-Type',file.endsWith('.css')?'text/css':file.endsWith('.js')?'text/javascript':'text/html');res.end(body)}catch{res.statusCode=404;res.end('Missing')}});
async function main(){await new Promise(r=>server.listen(8765,'127.0.0.1',r));const browser=await chromium.launch({headless:true,executablePath:process.env.RESTAURANT_CHROMIUM_PATH||(fs.existsSync('/tmp/chromium')?'/tmp/chromium':undefined),args:['--no-sandbox']});let checks=0;const context=await browser.newContext({serviceWorkers:'block'});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
await context.route('https://**',route=>route.fulfill({status:200,body:'',contentType:'text/javascript'}));
await context.route('**/scripts/restaurant-auth123.js*',route=>route.fulfill({body:'window.restaurantAuth123={shared:true,connect:async()=>window.mockDb};',contentType:'text/javascript'}));
await page.addInitScript(()=>{const owner='11111111-1111-4111-8111-111111111111';const item='22222222-2222-4222-8222-222222222222',cooked='88888888-8888-4888-8888-888888888888';const data={profiles:[{id:owner,full_name:'Test Cashier',role:'admin',status:'active'}],restaurant_members121:[],restaurant_presentation121:[],menu_categories104:[],menu_items104:[],pos_stock118:[],menu_ingredients105:[{id:'33333333-3333-4333-8333-333333333333',version:1,data:{code:'I',name:'Dry taco ingredients',currency:'LAK',unit:'kg',cost:30000,inventoryItemId118:item,inventoryFactor118:1}}],inventory_items104:[{id:item,data:{code:'I',name:'Dry taco ingredients',currency:'LAK',unit:'kg',cost:30000}},{id:cooked,data:{code:'C',name:'Cooked taco filling',currency:'LAK',unit:'kg',prepared124:true,cost:60000,fullPreparedCost124:80000}}],inventory_movements104:[{id:'receipt',data:{itemId:item,kind:'in',quantity:10,cost:30000},created_at:'2026-10-09T01:00:00Z'},{id:'production',data:{itemId:cooked,kind:'in',quantity:2,cost:60000},created_at:'2026-10-09T01:00:00Z'}],restaurant_batches124:[{id:'44444444-4444-4444-8444-444444444444',output_item_id:cooked,data:{name:'Taco filling',date:'2026-10-09',outputQuantity:2,stockUnit:'kg',currency:'LAK',ingredientTotal:120000,fullTotal:160000,ingredientUnitCost:60000,fullUnitCost:80000,cookingAdditionPercent:100/3,costMode:'actual'}}],restaurant_waste124:[]};window.mockFixtures=data;window.mockDb={auth:{onAuthStateChange(){},getSession:async()=>({data:{session:{user:{id:owner,email:'test@example.com'}}}}),signOut:async()=>({})},from(table){const q={select(){return q},order(){return q},eq(){return q},maybeSingle:async()=>({data:data[table]?.[0]||null}),single:async()=>({data:data[table]?.[0]||null}),then(resolve){return Promise.resolve({data:data[table]||[]}).then(resolve)}};return q},rpc:async()=>({error:{message:'failed to fetch'}})};window.supabase={};window.OJM_SUPABASE_URL='https://fixture.supabase.co';});
await page.goto('http://127.0.0.1:8765/');await page.waitForFunction(()=>document.querySelector('#restaurantApp')?.hidden===false);await page.evaluate(()=>switchTab('inv-preparation124'));await page.waitForFunction(()=>!!window.kitchen124);await page.evaluate(()=>switchTab('inv-preparation124'));await page.waitForSelector('#batchForm124');
await page.locator('#batchForm124 [name=name]').fill('Tacos test');await page.locator('#batchForm124 [name=outputItemId]').selectOption('88888888-8888-4888-8888-888888888888');await page.locator('#batchForm124 [name=outputQuantity]').fill('2');await page.locator('[data-input124] select').selectOption('33333333-3333-4333-8333-333333333333');await page.locator('[data-input124] input').fill('4');await page.locator('[name=minutes]').fill('60');await page.locator('[name=hourlyRate]').fill('30000');await page.locator('[name=energy]').fill('10000');assert((await page.locator('#batchPreview124').innerText()).includes('160,000'));checks++;
await page.evaluate(()=>switchTab('inv-waste124'));await page.waitForSelector('#wasteForm124');await page.locator('#wasteForm124 [name=itemId]').selectOption('88888888-8888-4888-8888-888888888888');await page.locator('#wasteForm124 [name=quantity]').fill('500');await page.locator('#wasteForm124 [name=unit]').selectOption('g');await page.locator('#wasteForm124 [name=reason]').fill('Food spoilage');assert((await page.locator('#wastePreview124').innerText()).includes('40,000'));checks++;
for(const [w,h,label] of [[1440,1000,'desktop'],[834,1194,'ipad'],[390,844,'phone']]){await page.setViewportSize({width:w,height:h});if(label==='phone'){await page.locator('#wasteForm124 [name=reason]').focus();assert.equal(await page.locator('#workspaceTools108').isVisible(),false);checks++}await page.waitForFunction(()=>innerWidth>1024||document.querySelector('#appSidebar').getBoundingClientRect().right<=0);await page.screenshot({path:path.join(__dirname,'results','waste-'+label+'.png'),fullPage:true});const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);assert(!overflow,label+' overflow');checks++}
await page.locator('#wastePreview124').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(__dirname,'results','waste-phone-cost.png')});await context.setOffline(true);await page.evaluate(()=>kitchen124.load());await page.waitForSelector('#wasteForm124');await page.locator('#wasteForm124 [name=itemId]').selectOption('88888888-8888-4888-8888-888888888888');await page.locator('#wasteForm124 [name=quantity]').fill('.5');await page.locator('#wasteForm124 [name=reason]').fill('Offline spoiled food');await page.locator('#wasteForm124 [type=submit]').click();await page.waitForFunction(()=>kitchen124.state.queue.length===1);assert.equal(await page.evaluate(()=>menuStore108.stock('88888888-8888-4888-8888-888888888888')),1.5);checks++;
await page.evaluate(()=>{kitchen124.state.queue=[];return kitchen124.load()});assert.equal(await page.evaluate(()=>kitchen124.state.queue.length),1);checks++;assert.deepEqual(errors,[]);checks++;
console.log(checks+' browser checks passed');fs.writeFileSync(require('path').join(__dirname,'results','browser-results.json'),JSON.stringify({checks,status:'passed'}));await browser.close();server.close()}
main().catch(e=>{console.error(e);server.close();process.exit(1)});
