module.exports=async function({db,root,ok,rejects,admin,staff,raw,cooked,ing,data,stocks,menu,order}){
 const fs=require('fs'),crypto=require('crypto');
 for(const file of ['10-pos-priority125.sql','11-restaurant-tabs125.sql'])await db.exec(fs.readFileSync(root+'/sql/'+file,'utf8'));
 ok('Priority and tab migrations install after preparation',true);
 for(const file of ['10-pos-priority125.sql','11-restaurant-tabs125.sql'])await db.exec(fs.readFileSync(root+'/sql/'+file,'utf8'));
 ok('Priority/tab migrations can be rerun safely',true);
 const snapshot=(await db.query('select pos_cashier_snapshot125() as s')).rows[0].s;
 ok('POS snapshot excludes stock movement history',snapshot.schema125&&snapshot.moves.length===0&&snapshot.stock.length===0);
 const balances=await stocks();ok('POS balances agree with full stock ledger',Object.entries(snapshot.balances125).every(([id,q])=>Number(q)===balances[id]));
 const unchanged=(await db.query('select pos_cashier_snapshot125($1) as s',[snapshot.catalogVersion125])).rows[0].s;
 ok('Unchanged catalog is omitted from background refresh',!Object.hasOwn(unchanged,'menu')&&!Object.hasOwn(unchanged,'ingredients'));
 const prior=await stocks();await db.query("select pos_order118($1,0,'pay',$2)",[order,{lines:[{menuId:menu,quantity:2}],service:'Dine in',payment:'Cash',confirmed:true,tendered:2000}]);
 ok('Repeated payment does not deduct stock a second time',JSON.stringify(prior)===JSON.stringify(await stocks()));
 const openId=crypto.randomUUID(),payload={lines:[{menuId:menu,quantity:1}],service:'Dine in',customer:'Two-iPad test'};
 const first=(await db.query("select pos_order118($1,0,'save',$2) as o",[openId,payload])).rows[0].o;
 const updated=(await db.query("select pos_order118($1,$2,'save',$3) as o",[openId,first.version,{...payload,customer:'Updated on iPad 1'}])).rows[0].o;
 await rejects(()=>db.query("select pos_order118($1,$2,'save',$3)",[openId,first.version,{...payload,customer:'Stale iPad 2'}]),/another device/,'A stale second-device edit is rejected');
 ok('Rejected second-device edit preserves the newer order',(await db.query('select data from pos_orders118 where id=$1',[openId])).rows[0].data.customer===updated.data.customer);
 // Grow closed history without adding stock movements; the operational payload stays bounded.
 await db.query(`insert into pos_orders118(id,number,status,data,created_by,paid_at) select gen_random_uuid(),(select coalesce(max(number),1000) from pos_orders118)+g,'paid',jsonb_build_object('lines','[]'::jsonb,'total',1,'payment','Cash'),$1,now() from generate_series(1,140) g`,[admin]);
 const many=(await db.query('select pos_cashier_snapshot125() as s')).rows[0].s;
 ok('Receipt list stays at 100 while the total count includes all sales',many.orders.filter(o=>o.status==='paid'||o.status==='refunded').length===100&&many.receiptCount125>100);
 ok('Current unpaid orders remain available despite large history',many.orders.some(o=>o.id===openId));
 ok('Today total is independent of receipt cap',Number(many.summary125.received)>=2140);
 await db.query(`insert into pos_orders118(id,number,status,data,created_by,paid_at) select gen_random_uuid(),(select coalesce(max(number),1000) from pos_orders118)+g,'paid',jsonb_build_object('lines','[]'::jsonb,'total',1,'payment','Cash'),$1,now()-interval '400 days' from generate_series(1,3000) g`,[admin]);
 const compactAfter=(await db.query('select pos_cashier_snapshot125() as s')).rows[0].s;
 const fullAfter=(await db.query('select pos_snapshot118() as s')).rows[0].s;
 ok('Three thousand historic sales do not enter the cashier snapshot',compactAfter.orders.length===many.orders.length&&compactAfter.receiptCount125===many.receiptCount125);
 ok('Cashier payload stays under one tenth of the full history payload',JSON.stringify(compactAfter).length<JSON.stringify(fullAfter).length/10);
 const report=(await db.query('select pos_report_page125(current_date,current_date) as rows')).rows[0].rows;
 ok('On-demand export contains records beyond the cashier receipt cap',report.length>100);
 const older=(await db.query('select pos_receipt_page125(current_date,$1) as rows',[Math.min(...many.orders.filter(o=>o.status==='paid').map(o=>o.number))])).rows[0].rows;
 ok('Older receipts load in a separate bounded page',older.length>0&&older.length<=100&&!older.some(o=>many.orders.some(m=>m.id===o.id)));
 await db.query('update restaurant_members121 set enabled=true,permissions=$2 where user_id=$1',[staff,{inventory:{view:true,prepare:true,stock_out:true,tabs:{'inv-preparation124':true,'inv-waste124':true}},pos:{view:true,sell:true,tabs:{'pos-sales-new':true}}}]);
 await db.query("select set_config('test.uid',$1,false)",[staff]);
 ok('Head cook preparation grant is accepted',(await db.query("select restaurant_tab_can125('inventory','inv-preparation124','prepare') as b")).rows[0].b);
 const version=(await db.query('select version from menu_ingredients105 where id=$1',[ing])).rows[0].version;
 await db.query('select restaurant_prepare124($1,$2)',[crypto.randomUUID(),{...data,inputs:[{ingredientId:ing,version,quantity:.1}],outputQuantity:.2}]);
 ok('Cook can prepare without general catalog edit grants',true);
 await db.query('select restaurant_record_waste124($1,$2)',[crypto.randomUUID(),{itemId:raw,date:'2026-10-09',quantity:.1,unit:'kg',reason:'Staff spoilage'}]);
 ok('Waste-only tab records loss through its guarded function',true);
 ok('Waste tab does not authorize manual stock-out',(await db.query("select restaurant_table_can121('inventory_movements104','edit',jsonb_build_object('kind','out')) as b")).rows[0].b===false);
 const restricted=(await db.query('select pos_cashier_snapshot125() as s')).rows[0].s;
 ok('Hidden receipt and open-order tabs omit those records',restricted.orders.length===0&&!restricted.summary125);
 const legacy=(await db.query('select pos_snapshot118() as s')).rows[0].s;
 ok('Restricted staff cannot bypass tab filtering using the old snapshot',legacy.schema125&&legacy.orders.length===0);
 await rejects(()=>db.query('select pos_report_page125($1,$2)',['2026-10-01','2026-10-09']),/Report access/,'Cashier cannot call restricted Management report');
 await db.query("update restaurant_members121 set permissions=jsonb_set(permissions,'{inventory,tabs,inv-waste124}','false') where user_id=$1",[staff]);
 await rejects(()=>db.query('select restaurant_record_waste124($1,$2)',[crypto.randomUUID(),{itemId:raw,date:'2026-10-09',quantity:.1,unit:'kg',reason:'No waste permission'}]),/Wastage access/,'Revoked waste tab blocks the server operation');
 // Exercise the real REST role: a preparation grant cannot bypass catalog RLS.
 await db.exec('grant usage on schema auth to authenticated; set role authenticated');
 await rejects(()=>db.query('insert into inventory_movements104(data) values($1)',[{itemId:raw,kind:'out',quantity:.1,reference:'Spoofed direct issue',waste124:crypto.randomUUID()}]),/row-level security|access required/,'Direct REST writes cannot spoof a preparation/waste function');
 await db.exec('reset role');await db.query("select set_config('test.uid',$1,false)",[admin]);
 const lastItem=crypto.randomUUID(),lastIngredient=crypto.randomUUID(),lastMenu=crypto.randomUUID();
 await db.query('insert into inventory_items104(id,data) values($1,$2)',[lastItem,{code:'LAST',name:'Last unit',currency:'LAK',unit:'g',cost:1}]);
 await db.query('insert into inventory_movements104(data) values($1)',[{itemId:lastItem,kind:'in',quantity:1,reference:'One available unit'}]);
 await db.query('insert into menu_ingredients105(id,data) values($1,$2)',[lastIngredient,{code:'LAST-I',name:'Last unit ingredient',unit:'g',currency:'LAK',cost:1,purchaseQuantity:1,purchasePrice:1,inventoryItemId118:lastItem,inventoryFactor118:1}]);
 await db.query('insert into menu_items104(id,data) values($1,$2)',[lastMenu,{code:'LAST-M',name:'Last unit menu',price:100,currency:'LAK',recipe:[{itemId:lastIngredient,quantity:1}]}]);
 const lastPayload={lines:[{menuId:lastMenu,quantity:1}],service:'Takeaway',payment:'Bank',paymentReference:'Confirmed bank transfer',confirmed:true};
 await db.query("update restaurant_members121 set permissions=jsonb_set(permissions,'{pos,tabs,pos-overview}','true') where user_id=$1",[staff]);
 await db.query("select set_config('test.uid',$1,false)",[staff]);await db.query("select pos_manage118('open','{\"amount\":0}',0)");
 await db.query("select set_config('test.uid',$1,false)",[staff]);await db.query("select pos_order118($1,0,'pay',$2)",[crypto.randomUUID(),lastPayload]);
 await db.query("select set_config('test.uid',$1,false)",[admin]);
 await rejects(()=>db.query("select pos_order118($1,0,'pay',$2)",[crypto.randomUUID(),lastPayload]),/Insufficient stock/,'Another cashier cannot sell stock consumed by the first cashier');
 ok('Last-unit stock remains zero after rejected second sale',Number((await db.query('select restaurant_stock124($1) as q',[lastItem])).rows[0].q)===0);
};
