-- Run in the existing Supabase SQL Editor after the v117 database update.
-- Additive POS tables. Existing menus, accounts and journal entries are preserved.
begin;
create table if not exists public.pos_config118(id boolean primary key default true check(id),data jsonb not null default '{"methods":["Cash","BCEL QR","Bank"],"cashiers":[],"discountLimit":10,"receiptWidth":80,"receiptFooter":"Thank you for visiting."}'::jsonb,version integer not null default 1);
insert into public.pos_config118(id) values(true) on conflict do nothing;
create table if not exists public.pos_orders118(id uuid primary key,number bigint generated by default as identity unique,status text not null default 'unpaid' check(status in ('unpaid','paid','cancelled','refunded')),data jsonb not null,version integer not null default 1,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid not null references public.profiles(id),paid_at timestamptz,refunded_at timestamptz);
create table if not exists public.pos_shifts118(id uuid primary key default gen_random_uuid(),cashier uuid not null references public.profiles(id),opened_at timestamptz not null default now(),closed_at timestamptz,opening numeric not null check(opening>=0),counted numeric,expected numeric);
create unique index if not exists pos_one_open_shift118 on public.pos_shifts118(cashier) where closed_at is null;
create table if not exists public.pos_cash118(id uuid primary key default gen_random_uuid(),shift_id uuid not null references public.pos_shifts118(id),amount numeric not null check(amount<>0),reason text not null,created_at timestamptz not null default now(),created_by uuid not null references public.profiles(id));
create table if not exists public.pos_stock118(id uuid primary key default gen_random_uuid(),order_id uuid not null references public.pos_orders118(id),item_id uuid not null references public.inventory_items104(id),quantity numeric not null check(quantity<>0),kind text not null check(kind in ('sale','return')),created_at timestamptz not null default now(),created_by uuid not null references public.profiles(id),unique(order_id,item_id,kind));
create or replace function public.pos_allowed118() returns boolean language sql stable security definer set search_path=public,pg_temp as $$select auth.uid() is not null and (public.is_admin() or exists(select 1 from public.pos_config118 where data->'cashiers' ? auth.uid()::text))$$;
do $$declare t text;begin foreach t in array array['pos_config118','pos_orders118','pos_shifts118','pos_cash118','pos_stock118'] loop execute format('alter table public.%I enable row level security',t);execute format('revoke all on public.%I from anon,authenticated',t);execute format('grant select on public.%I to authenticated',t);execute format('drop policy if exists pos_read118 on public.%I',t);execute format('create policy pos_read118 on public.%I for select to authenticated using(public.pos_allowed118())',t);end loop;end$$;
-- All changes happen through validated, permission-checked functions below.
create or replace function public.pos_snapshot118() returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
begin
 if not public.pos_allowed118() then raise exception 'Ask an administrator to enable your POS access';end if;
 return jsonb_build_object('config',(select data from pos_config118 where id),'configVersion',(select version from pos_config118 where id),'menu',coalesce((select jsonb_agg(to_jsonb(m)) from menu_items104 m),'[]'::jsonb),'ingredients',coalesce((select jsonb_agg(to_jsonb(m)) from menu_ingredients105 m),'[]'::jsonb),'items',coalesce((select jsonb_agg(to_jsonb(m)) from inventory_items104 m),'[]'::jsonb),'categories',coalesce((select jsonb_agg(to_jsonb(m)) from menu_categories104 m),'[]'::jsonb),'moves',coalesce((select jsonb_agg(to_jsonb(m)) from inventory_movements104 m),'[]'::jsonb),'stock',coalesce((select jsonb_agg(to_jsonb(m)) from pos_stock118 m),'[]'::jsonb),'orders',coalesce((select jsonb_agg(to_jsonb(m) order by m.created_at desc) from pos_orders118 m),'[]'::jsonb),'shifts',coalesce((select jsonb_agg(to_jsonb(m)) from pos_shifts118 m),'[]'::jsonb),'cash',coalesce((select jsonb_agg(to_jsonb(m)) from pos_cash118 m),'[]'::jsonb));
end$$;
-- Recursively expand bundles into ingredient quantities. Cycles are rejected.
create or replace function public.pos_recipe118(p_menu uuid,p_quantity numeric,p_seen uuid[] default '{}') returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare d jsonb;l jsonb;result jsonb='[]';begin
 if p_menu=any(p_seen) or cardinality(p_seen)>12 then raise exception 'Recipe contains a circular bundle';end if;
 select data into d from menu_items104 where id=p_menu;
 if d is null or d->>'active'='false' then raise exception 'Menu item unavailable';end if;
 for l in select value from jsonb_array_elements(coalesce(d->'recipe','[]')) loop
  if coalesce((l->>'quantity')::numeric,0)<=0 then raise exception 'Invalid recipe quantity';end if;
  if d->>'itemType'='bundle' then result=result||pos_recipe118((l->>'itemId')::uuid,(l->>'quantity')::numeric*p_quantity,p_seen||p_menu);
  else result=result||jsonb_build_array(jsonb_build_object('itemId',l->>'itemId','quantity',(l->>'quantity')::numeric*p_quantity));end if;
 end loop;return result;end$$;
create or replace function public.pos_order118(p_id uuid,p_version integer,p_action text,p_data jsonb default '{}') returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare old pos_orders118;result pos_orders118;line jsonb;d jsonb;g jsonb;o jsonb;pick jsonb;recipe jsonb;ing jsonb;r jsonb;item inventory_items104;config jsonb;lines jsonb='[]';uses jsonb='[]';choices jsonb;names jsonb;qty numeric;price numeric;subtotal numeric=0;discount numeric;amount numeric;on_hand numeric;consumption numeric;sid uuid;method text;count_selected integer;ref text;
begin
 if not pos_allowed118() then raise exception 'POS access required';end if;
 if p_id is null or p_action not in ('save','pay','cancel','refund') then raise exception 'Invalid order action';end if;
 perform pg_advisory_xact_lock(118,118);
 perform pg_advisory_xact_lock(hashtextextended(p_id::text,118));
 select * into old from pos_orders118 where id=p_id for update;
 select data into config from pos_config118 where id;
 if old.id is not null and old.status=p_action then return to_jsonb(old);end if;
 -- Repeated payment requests return the original receipt; never consume twice.
 if p_action='pay' and old.status='paid' then return to_jsonb(old);end if;
 if p_action='refund' and old.status='refunded' then return to_jsonb(old);end if;
 if old.id is not null and old.version<>p_version then raise exception 'Order changed on another device. Reload before continuing';end if;
 if old.id is null and p_version<>0 then raise exception 'Order no longer exists';end if;
 if p_action in ('cancel','refund') then
  if old.id is null then raise exception 'Save the order first';end if;
  if p_action='cancel' and old.status<>'unpaid' then raise exception 'Only unpaid orders can be cancelled';end if;
  if p_action='refund' and (old.status<>'paid' or not public.is_admin()) then raise exception 'An administrator must approve a paid-order refund';end if;
  if length(trim(coalesce(p_data->>'reason','')))<3 then raise exception 'Enter a reason';end if;
  if p_action='refund' and old.data->>'payment'='Cash' then select id into sid from pos_shifts118 where cashier=auth.uid() and closed_at is null for update;if sid is null then raise exception 'Open your shift before refunding cash';end if;end if;
  if p_action='refund' and coalesce((p_data->>'restock')::boolean,false) then
   for r in select to_jsonb(x) from pos_stock118 x where order_id=p_id and kind='sale' order by item_id loop
    perform 1 from inventory_items104 where id=(r->>'item_id')::uuid for update;
    insert into pos_stock118(order_id,item_id,quantity,kind,created_by) values(p_id,(r->>'item_id')::uuid,-(r->>'quantity')::numeric,'return',auth.uid());
   end loop;
  end if;
  update pos_orders118 set status=case when p_action='refund' then 'refunded' else 'cancelled' end,version=version+1,updated_at=now(),refunded_at=case when p_action='refund' then now() else null end,data=data||jsonb_build_object('reason',p_data->>'reason','restocked',coalesce((p_data->>'restock')::boolean,false),'actionBy',auth.uid(),'refundShiftId',sid) where id=p_id returning * into result;return to_jsonb(result);
 end if;
 if old.id is not null and old.status<>'unpaid' then raise exception 'This order is already closed';end if;
 if coalesce(jsonb_typeof(p_data->'lines'),'')<>'array' or jsonb_array_length(p_data->'lines') not between 1 and 100 then raise exception 'Add between 1 and 100 order lines';end if;
 if coalesce(p_data->>'service','') not in ('Dine in','Takeaway','Delivery','Online') or length(coalesce(p_data->>'customer',''))>200 or length(coalesce(p_data->>'note',''))>2000 then raise exception 'Invalid order details';end if;
 for line in select value from jsonb_array_elements(p_data->'lines') loop
  select data into d from menu_items104 where id=(line->>'menuId')::uuid;
  if d is null or d->>'active'='false' or d->>'currency'<>'LAK' then raise exception 'Choose an available LAK menu item';end if;
  qty=(line->>'quantity')::numeric;if qty is null or qty<>trunc(qty) or qty not between 1 and 999 then raise exception 'Invalid order quantity';end if;
  price=(d->>'price')::numeric;if price is null or price<0 or price>1000000000 then raise exception 'Invalid menu price';end if;
  recipe=pos_recipe118((line->>'menuId')::uuid,1);choices='{}';names='[]';
  for g in select value from jsonb_array_elements(coalesce(d->'posOptions118','[]')) loop
   pick=coalesce(line->'choices'->(g->>'id'),'[]');if jsonb_typeof(pick)<>'array' then raise exception 'Invalid customization';end if;
   count_selected=jsonb_array_length(pick);
   if count_selected<coalesce((g->>'min')::integer,0) or count_selected>coalesce((g->>'max')::integer,1) then raise exception 'Review choices for %',g->>'name';end if;
   if (select count(distinct value) from jsonb_array_elements(pick))<>count_selected then raise exception 'Duplicate choice';end if;
   if count_selected>0 then select coalesce(jsonb_agg(x),'[]') into recipe from jsonb_array_elements(recipe) x where not coalesce(g->'replaces','[]') ? (x->>'itemId');end if;
   for ref in select jsonb_array_elements_text(pick) loop
    select x into o from jsonb_array_elements(g->'options') x where x->>'id'=ref;
    if o is null or o->>'available'='false' then raise exception 'An option is unavailable';end if;
    if coalesce((o->>'price')::numeric,0)<0 then raise exception 'Invalid option price';end if;
    price=price+coalesce((o->>'price')::numeric,0);recipe=recipe||coalesce(o->'recipe','[]');names=names||jsonb_build_array(o->>'name');
   end loop;choices=choices||jsonb_build_object(g->>'id',pick);
  end loop;
  if p_action='pay' then
   if jsonb_array_length(recipe)=0 and coalesce(d->>'posNoStock118','false')<>'true' then raise exception 'Link the recipe to Inventory, or mark this item as non-stock in POS Management';end if;
   for r in select value from jsonb_array_elements(recipe) loop
    select data into ing from menu_ingredients105 where id=(r->>'itemId')::uuid;
    if ing is null or ing->>'active'='false' or coalesce(ing->>'inventoryItemId118','')='' then raise exception 'Link every selected ingredient to Inventory in POS Management';end if;
    amount=(r->>'quantity')::numeric*coalesce((ing->>'inventoryFactor118')::numeric,1)*qty;
    if amount is null or amount<=0 then raise exception 'Invalid ingredient unit conversion';end if;
    uses=uses||jsonb_build_array(jsonb_build_object('itemId',ing->>'inventoryItemId118','quantity',amount));
   end loop;
  end if;
  subtotal=subtotal+round(price*qty,2);lines=lines||jsonb_build_array(jsonb_build_object('menuId',line->>'menuId','name',d->>'name','photoData',d->>'photoData','photo118',d->>'photo118','quantity',qty,'unitPrice',price,'choices',choices,'options',names,'note',left(coalesce(line->>'note',''),500)));
 end loop;
 discount=coalesce((p_data->>'discount')::numeric,0);if p_data->>'discountType'='percent' then discount=round(subtotal*discount/100,2);end if;
 if discount<0 or discount>subtotal then raise exception 'Discount exceeds the order amount';end if;
 if not is_admin() and discount>subtotal*coalesce((config->>'discountLimit')::numeric,0)/100 then raise exception 'This discount requires administrator approval';end if;
 method=p_data->>'payment';
 if p_action='pay' then
  if method is null or not config->'methods' ? method or coalesce(p_data->>'confirmed','false')<>'true' then raise exception 'Confirm the actual payment received';end if;
  if method<>'Cash' and length(trim(coalesce(p_data->>'paymentReference','')))<3 then raise exception 'Enter the verified bank payment reference';end if;
  select id into sid from pos_shifts118 where cashier=auth.uid() and closed_at is null for update;
  if sid is null then raise exception 'Open your shift in Overview before charging';end if;
  if method='Cash' and coalesce((p_data->>'tendered')::numeric,0)<subtotal-discount then raise exception 'Cash received is less than the total';end if;
 end if;
 insert into pos_orders118(id,number,data,created_by) select p_id,coalesce(max(number),1000)+1,'{}',auth.uid() from pos_orders118 on conflict(id) do nothing;
 if p_action='pay' then
  for r in select jsonb_build_object('itemId',x->>'itemId','quantity',sum((x->>'quantity')::numeric)) from jsonb_array_elements(uses) x group by x->>'itemId' order by x->>'itemId' loop
   select * into item from inventory_items104 where id=(r->>'itemId')::uuid for update;
   if item.id is null or item.data->>'active'='false' then raise exception 'Inventory item unavailable';end if;
   select coalesce(sum(case when data->>'kind' in ('in','adjust-in') then (data->>'quantity')::numeric else -(data->>'quantity')::numeric end),0) into on_hand from inventory_movements104 where data->>'itemId'=item.id::text;
   select coalesce(sum(quantity),0) into consumption from pos_stock118 where item_id=item.id;
   if on_hand-consumption<(r->>'quantity')::numeric then raise exception 'Insufficient stock: %',item.data->>'name';end if;
   insert into pos_stock118(order_id,item_id,quantity,kind,created_by) values(p_id,item.id,(r->>'quantity')::numeric,'sale',auth.uid());
  end loop;
 end if;
 update pos_orders118 set data=jsonb_build_object('lines',lines,'service',p_data->>'service','customer',left(coalesce(p_data->>'customer',''),200),'note',left(coalesce(p_data->>'note',''),2000),'subtotal',subtotal,'discount',discount,'discountType','amount','total',subtotal-discount,'currency','LAK','payment',case when p_action='pay' then method else null end,'paymentReference',p_data->>'paymentReference','tendered',p_data->>'tendered','shiftId',sid,'cashier',(select full_name from profiles where id=auth.uid())),status=case when p_action='pay' then 'paid' else 'unpaid' end,version=coalesce(old.version,0)+1,updated_at=now(),paid_at=case when p_action='pay' then now() else null end where id=p_id returning * into result;
 return to_jsonb(result);
end$$;
create or replace function public.pos_manage118(p_action text,p_data jsonb,p_version integer default 0) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare s pos_shifts118;r jsonb;expected_amount numeric;v integer;begin
 if not pos_allowed118() then raise exception 'POS access required';end if;
 if p_action='config' then
  if not is_admin() then raise exception 'Administrator access required';end if;
  if jsonb_typeof(p_data->'methods')<>'array' or jsonb_array_length(p_data->'methods')=0 or exists(select 1 from jsonb_array_elements_text(p_data->'methods') x where x not in ('Cash','BCEL QR','Bank')) or jsonb_typeof(p_data->'cashiers')<>'array' or coalesce((p_data->>'discountLimit')::numeric,-1) not between 0 and 100 or coalesce((p_data->>'receiptWidth')::integer,0) not in(58,80) then raise exception 'Invalid POS settings';end if;
  update pos_config118 set data=p_data,version=version+1 where id and version=p_version returning version into v;if v is null then raise exception 'Settings changed. Reload before saving';end if;return jsonb_build_object('version',v);
 elsif p_action='open' then
  if coalesce((p_data->>'amount')::numeric,-1)<0 then raise exception 'Enter the opening cash float';end if;
  insert into pos_shifts118(cashier,opening) values(auth.uid(),(p_data->>'amount')::numeric) returning to_jsonb(pos_shifts118.*) into r;return r;
 end if;
 select * into s from pos_shifts118 where cashier=auth.uid() and closed_at is null for update;if s.id is null then raise exception 'Open a shift first';end if;
 if p_action='cash' then
  if coalesce((p_data->>'amount')::numeric,0)=0 or length(trim(coalesce(p_data->>'reason','')))<3 then raise exception 'Enter a nonzero cash movement and reason';end if;
  insert into pos_cash118(shift_id,amount,reason,created_by) values(s.id,(p_data->>'amount')::numeric,p_data->>'reason',auth.uid()) returning to_jsonb(pos_cash118.*) into r;return r;
 elsif p_action='close' then
  if coalesce((p_data->>'amount')::numeric,-1)<0 then raise exception 'Enter the counted cash';end if;
  select s.opening+coalesce((select sum(amount) from pos_cash118 where shift_id=s.id),0)+coalesce((select sum((data->>'total')::numeric) from pos_orders118 where data->>'shiftId'=s.id::text and data->>'payment'='Cash' and status in('paid','refunded')),0)-coalesce((select sum((data->>'total')::numeric) from pos_orders118 where data->>'payment'='Cash' and status='refunded' and data->>'refundShiftId'=s.id::text),0) into expected_amount;
  update pos_shifts118 set closed_at=now(),counted=(p_data->>'amount')::numeric,expected=expected_amount where id=s.id returning to_jsonb(pos_shifts118.*) into r;return r;
 end if;raise exception 'Unknown management action';end$$;
-- Keep manual Inventory issues consistent with POS stock consumption.
create or replace function public.pos_inventory_guard118() returns trigger language plpgsql security definer set search_path=public,pg_temp as $$
declare available numeric;begin
 if new.data->>'kind' not in ('out','adjust-out') then return new;end if;
 perform 1 from inventory_items104 where id::text=new.data->>'itemId' for update;
 select coalesce(sum(case when data->>'kind' in ('in','adjust-in') then (data->>'quantity')::numeric else -(data->>'quantity')::numeric end),0)-(select coalesce(sum(quantity),0) from pos_stock118 where item_id::text=new.data->>'itemId') into available from inventory_movements104 where data->>'itemId'=new.data->>'itemId';
 if available<(new.data->>'quantity')::numeric then raise exception 'Insufficient stock after POS sales';end if;return new;end$$;
drop trigger if exists pos_inventory_guard118 on public.inventory_movements104;
create trigger pos_inventory_guard118 before insert on public.inventory_movements104 for each row execute function public.pos_inventory_guard118();
revoke all on function public.pos_recipe118(uuid,numeric,uuid[]) from public,anon,authenticated;
revoke all on function public.pos_snapshot118(),public.pos_order118(uuid,integer,text,jsonb),public.pos_manage118(text,jsonb,integer),public.pos_allowed118(),public.pos_inventory_guard118() from public,anon;
grant execute on function public.pos_snapshot118(),public.pos_order118(uuid,integer,text,jsonb),public.pos_manage118(text,jsonb,integer),public.pos_allowed118() to authenticated;
-- Include POS data in application backup packages when the v117 registry exists.
do $$begin if to_regclass('public.backup_registry113') is not null then
 insert into public.backup_registry113(table_name,pk_columns,date_path) values
 ('pos_config118',array['id'],null),('pos_orders118',array['id'],array['created_at']),('pos_shifts118',array['id'],array['opened_at']),('pos_cash118',array['id'],null),('pos_stock118',array['id'],null)
 on conflict(table_name) do update set pk_columns=excluded.pk_columns,date_path=excluded.date_path;
 end if;end$$;
commit;

